### ISSUE TITLE
Position of errors

### ISSUE THREAD

**Issue by jonsterling** [konn/vscode-redtt-diagnostics#2]
Wow, thank you for writing this! It's really cool :smiley: 

I noticed a small bug. If I have a parse error, the diagnostic tooltip shows up at the beginning of the document instead of at the reported location.

**Comment by konn** [comment]
Thank you for the report!
Currently, this extension just parses the error report from `redtt` to retrieve the error location and uses dummy location 0:0 if no location information found.
So the possible cause here is either that the extension's location error parsing logic doesn't work properly or that the `redtt` executable doesn't report the location for that parsing error.

Could you provide the original parsing error output generated by`redtt`?

**Comment by jonsterling** [comment]
Certainly! I will look into this when I have a free moment (today I am creating homeworks for my students)

**Comment by konn** [comment]
@jonsterling Do you have enough time for reproducing example?

**Comment by jonsterling** [comment]
Hi! Sorry for the delay, I was busy all week. I will try and fit it in today.

**Comment by jonsterling** [comment]
Here's an example. Try the following code:

```
data s1 where
| base
| loop (i : 𝕀) [∂[i] → base]

asdf
```

Running `redtt`, the output is:

```
/home/jon/Source/redtt/library/data/s1.red:5.0-5.4 [Error]:
  Parse error
```

But the editor reports the error on the word `data`.

**Comment by konn** [comment]
@jonsterling Thank you for an example! It must now be fixed.

**Comment by jonsterling** [comment]
Awesome, thank you! I just tried out the new version and it works. Very cool!
